# Generated by Django 3.2.6 on 2021-09-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environmental_Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light_on', models.DateTimeField(blank=True, null=True)),
                ('light_duration', models.DateTimeField(blank=True, null=True)),
                ('temperature_max', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('temperature_min', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('humidity_max', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('humidity_min', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('vpd_targeting', models.BooleanField()),
                ('vpd_target', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor_Logs',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False, unique=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('vpd', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('lux', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('soil_moisture', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sensor_id', models.CharField(max_length=24)),
            ],
        ),
    ]
