# Generated by Django 3.2.6 on 2021-08-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atmospheric',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False, unique=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('kpa', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('vpd', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
        ),
    ]
