# Generated by Django 3.2.6 on 2021-09-20 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steve_sense', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environmental_settings',
            name='light_duration',
        ),
    ]
