# Generated by Django 3.2.6 on 2021-09-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steve_sense', '0003_environmental_settings_light_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmental_settings',
            name='vpd_targeting',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
