# Generated by Django 3.2.6 on 2021-09-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steve_sense', '0004_alter_environmental_settings_vpd_targeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmental_settings',
            name='light_on',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
