# Generated by Django 3.2.6 on 2021-09-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steve_sense', '0005_alter_environmental_settings_light_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmental_settings',
            name='light_timer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmental_settings',
            name='thermostat',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
