# Generated by Django 3.2.6 on 2021-09-29 14:16

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steve_sense', '0006_auto_20210924_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attached_Devices',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('device_type', models.CharField(choices=[('light', 'light'), ('light rail', 'light rail'), ('heater', 'heater'), ('extractor', 'extractor'), ('circulating fans', 'circulating fans'), ('aircon', 'aircon'), ('dehumidifier', 'dehumidifier')], max_length=24)),
                ('device_relay_channel', models.IntegerField(choices=[(1, 'CH1'), (2, 'CH2'), (3, 'CH3'), (4, 'CH4'), (5, 'CH5'), (6, 'CH6'), (7, 'CH7'), (8, 'CH8')])),
                ('device_location', models.CharField(max_length=24)),
                ('device_duty_cycle', models.BooleanField(default=False)),
                ('duty_cycle_pulse_width', models.DurationField(blank=True, null=True)),
                ('duty_cycle_time_period', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attached_Senors',
            fields=[
                ('sensor_id', models.CharField(max_length=24, primary_key=True, serialize=False, unique=True)),
                ('sensor_location', models.CharField(max_length=24)),
                ('sensor_capabilities', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='environmental_settings',
            name='humidity_max',
        ),
        migrations.RemoveField(
            model_name='environmental_settings',
            name='humidity_min',
        ),
        migrations.RemoveField(
            model_name='environmental_settings',
            name='temperature_max',
        ),
        migrations.RemoveField(
            model_name='environmental_settings',
            name='temperature_min',
        ),
        migrations.RemoveField(
            model_name='environmental_settings',
            name='thermostat',
        ),
        migrations.AddField(
            model_name='environmental_settings',
            name='auto_sync_rail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='environmental_settings',
            name='circulating_fans',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='environmental_settings',
            name='circulating_fans_time_pattern',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmental_settings',
            name='cooling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='environmental_settings',
            name='cooling_target',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)]),
        ),
        migrations.AddField(
            model_name='environmental_settings',
            name='cooling_target_deviation',
            field=models.DecimalField(decimal_places=2, default=0.05, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0.5)]),
        ),
        migrations.AddField(
            model_name='environmental_settings',
            name='differential_extractor_priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='environmental_settings',
            name='differential_target_deviation',
            field=models.DecimalField(decimal_places=2, default=0.05, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0.5)]),
        ),
        migrations.AddField(
            model_name='environmental_settings',
            name='enabled_devices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='environmental_settings',
            name='extractor_differential_analysis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='environmental_settings',
            name='extractor_humidity_control_targeting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='environmental_settings',
            name='extractor_off_humidity',
            field=models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='environmental_settings',
            name='extractor_on_humidity',
            field=models.IntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='environmental_settings',
            name='extractor_time_pattern',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmental_settings',
            name='extractor_timer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='environmental_settings',
            name='heating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='environmental_settings',
            name='heating_target',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)]),
        ),
        migrations.AddField(
            model_name='environmental_settings',
            name='heating_target_deviation',
            field=models.DecimalField(decimal_places=2, default=0.05, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0.5)]),
        ),
        migrations.AddField(
            model_name='environmental_settings',
            name='humidity_differential_target',
            field=models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='environmental_settings',
            name='light_intensity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='environmental_settings',
            name='light_intensity_time_pattern',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmental_settings',
            name='light_rail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='environmental_settings',
            name='light_rail_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmental_settings',
            name='light_rail_on',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmental_settings',
            name='temperature_differential_target',
            field=models.IntegerField(default=23, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)]),
        ),
        migrations.AddField(
            model_name='environmental_settings',
            name='temperature_humidity_bias',
            field=models.DecimalField(decimal_places=2, default=0.05, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0.5)]),
        ),
        migrations.AlterField(
            model_name='environmental_settings',
            name='light_timer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='environmental_settings',
            name='vpd_target',
            field=models.DecimalField(decimal_places=2, default=0.05, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='environmental_settings',
            name='vpd_targeting',
            field=models.BooleanField(default=False),
        ),
    ]
