# Generated by Django 3.2.6 on 2021-09-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steve_sense', '0007_auto_20210929_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environmental_settings',
            name='id',
        ),
        migrations.AddField(
            model_name='environmental_settings',
            name='space_id',
            field=models.CharField(default='tent1', max_length=24, primary_key=True, serialize=False, unique=True),
        ),
    ]
