# Generated by Django 3.2.6 on 2021-12-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steve_sense', '0009_auto_20211219_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmental_settings',
            name='extractor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attached_devices',
            name='device_type',
            field=models.CharField(choices=[('light', 'light'), ('light rail', 'light rail'), ('heater', 'heater'), ('extractor', 'extractor'), ('circulating fans', 'circulating fans'), ('aircon', 'aircon'), ('dehumidifier', 'dehumidifier')], max_length=24, unique=True),
        ),
    ]
