# Generated by Django 3.2.6 on 2021-12-29 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steve_sense', '0010_auto_20211228_1520'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attached_Senors',
            new_name='Attached_Sensors',
        ),
    ]
