# Generated by Django 3.2.6 on 2021-12-31 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steve_sense', '0011_rename_attached_senors_attached_sensors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environmental_settings',
            name='differential_extractor_priority',
        ),
        migrations.RemoveField(
            model_name='environmental_settings',
            name='differential_target_deviation',
        ),
        migrations.RemoveField(
            model_name='environmental_settings',
            name='extractor_differential_analysis',
        ),
        migrations.RemoveField(
            model_name='environmental_settings',
            name='extractor_off_humidity',
        ),
        migrations.RemoveField(
            model_name='environmental_settings',
            name='extractor_on_humidity',
        ),
        migrations.RemoveField(
            model_name='environmental_settings',
            name='humidity_differential_target',
        ),
        migrations.RemoveField(
            model_name='environmental_settings',
            name='temperature_differential_target',
        ),
        migrations.RemoveField(
            model_name='environmental_settings',
            name='temperature_humidity_bias',
        ),
        migrations.AddField(
            model_name='environmental_settings',
            name='extractor_humidity_target_deviation',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
