# Generated by Django 3.2.6 on 2021-12-31 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steve_sense', '0013_auto_20211231_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor_logs',
            name='space',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='steve_sense.space'),
        ),
    ]
