# Generated by Django 3.2.6 on 2021-12-31 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steve_sense', '0014_alter_sensor_logs_space'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor_logs',
            name='space',
        ),
    ]
